### ISSUE TITLE
New Feature: Auto divide Flow

### ISSUE THREAD

**Issue by mariagnoriegag** [minskylab/plexo-platform#100]
I'm building this

I tried to do this:
1. Click to button auto divide
2. Then open something like this
<img width="1307" alt="image" src="https://github.com/minskylab/plexo-platform/assets/25857636/86eb99bd-4e1a-4d18-925c-8dbce6b378b8">
And more... (thinking)

**Comment by annalbirena** [comment]
Auto divide task Flow implemented with PR #106
