### ISSUE TITLE
UXI/UI error refresh task

### ISSUE THREAD

**Issue by VktorR** [minskylab/plexo-platform#74]
I tried to update a task that I had recently changed and a "no found" scree was shown.

I changed the "lead by" of a task.
I clicked the task too check if the change was made.
I refreshed and a white screen appeared.
The message was: "not found".
The error occured more than once.

![image](https://github.com/minskylab/plexo-platform/assets/134090955/7c652e2e-2a53-4d66-8d21-51de3b952d4e)

**Comment by AlvaroZev** [comment]
solved in gamma cargo instance
