### ISSUE TITLE
UX/UI: A list of errors ocurred in TASK DETAIL VIEW, not changing some fields

### ISSUE THREAD

**Issue by mariagnoriegag** [minskylab/plexo-platform#79]
The list of fields not updating:
* Status
* Priority
* Lead
* Asignee 
* Due date

Then it works all, except:
* Due date

Labels and project are working.

Sometimes works, sometimes dont work

<img width="1122" alt="image" src="https://github.com/minskylab/plexo-platform/assets/25857636/948adeda-5a6c-4b9e-ab6c-0f8a5e490c45">

**Comment by AlvaroZev** [comment]
falta due_date

**Comment by AlvaroZev** [comment]
se corrigió due_date en task detail y project detail
